FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
ENV FENCE_ONNX_PATH=/app/best.onnx
EXPOSE 8080
CMD ["uvicorn", "app:app", "--host","0.0.0.0","--port","8080"]
